### ISSUE TITLE
Temptative page as a redirect URL.

### ISSUE THREAD

**Issue by sfmullen** [edujtm/diversify#17]
I've been playing around with a little bit of JS and CSS to come up with this sketch for a more user friendly experience for the authentication process.

Site: https://macmullen.github.io/diversify-test-page/

If it is authorized through the Spotify Developers settings as a redirect URL and used inside the .env file it should work as intended.

If accepted, I could PR the files to be used a Github Page for this project.

**Comment by edujtm** [comment]
That's awesome. That sure would help, redirecting to localhost is software gore at its finest. I'll definitely accept it.
